fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default value
    service:
        mailer: fos_user.mailer.twig_swift
    from_email: # Use this node only if you don't want the global email address for the confirmation email
        address: %mailer_user%
        sender_name: %app_name%
    registration:
        confirmation:
            enabled:    true
            template:   ApplicationMainBundle:Email:registration.email.twig
        form:
#            type:               user_registration
            name:               fos_user_registration_form
            validation_groups:  [Registration, Default]
